// Acoustic Main 'Database'
Table RockHallSalesforce {
  //Acoustic System fields
  Opt_In_Details System
  Email_Type System
  CRM_Account_ID System
  CRM_Enable_Sync System
  Opted_Out_Date System
  CRM_Sync_ID System
  Email System
  CRM_Lead_Source System
  Last_Modified_Date System
  Opt_Out_Details System
  CRM_Contact_Type System
  Opt_In_Date System
  CREATED_FROM System
  // Salesforce Contact / Lead fields
  SF_Contact_Id Text
  SF_Lead_Id Text
  SF_FirstName Text
  SF_LastName Text
}

// bunlde of Opps and OppLineItems
Table OppsAndLineItems {
  COMBOKEY "Sync Id"
  //Opportunity fields
  "Oportunity Id" "Sync Id"
  "Account Id" "Sync Id"
  "Primary Contact Id"  "Sync Id"
  "CloseDate"  Date
  "Donor Type" Text
  "Fund Name" Text
  "Member Level" Text
  "Membership End Date" Date
  "Membership Fulfilled" "Yes/ No"
  "Membership Type" Text
  "Most Recent Membership" Date
  "Stage" Text
  "Ticketure Channel" Text
  "Ticketure Order Number" Text
  "Total Donation Amount" Number
  "Total Membership Amount" Number
  
  // Line Item fields
  "Opp Line Item Id" "Sync Id"
  "Opportunity Parent Id" "Sync Id"
  "Product Code" Text
  "Product Name" Text
  "Product Type" Text
  "Quantity" Numeric
  "Sales Price" Numeric
  "Total Price" Numeric
  "Ticketure Event Category" Text
  "Ticketure Event Session End Date Time" Date
  "Ticketure Event Session Start Date Time" Date
  "Ticketure Occurred At Date and Time" Date
  "Ticketure Redeemed Date Time" Date
  "Ticketure Status" Text
  "Ticketure Ticket Group" Text
  
}

// Bundle of Orders and OrderLineItems
// Bundle of Orders and OrderLineItems
Table OrdersAndLineItems {
	COMBOKEY "Sync Id"

	// Order fields
	"Order Id" "Sync Id"
	"Accout Id" "Sync Id"
	"Bill To Contact Id" "Sync Id"
	"Opportunity Id" "Sync Id"
	"Order Description" "Text"
	"Order Amount" "Numeric"
	"Order Name" "Text"
	"Order Number" "Text"
	"Order Status" "Text"
	"Shopify Account Email" "Email"
	"Shopify Customer Email" "Email"

	// Item Fields
	"Order Item Id" "Sync Id"
	"Order Parent Id" "Sync Id"
	"Product Id" "Sync Id"
	"Product Name" "Text"
	"Product Type" "Text"
	"Item Description" "Text"
	"List Price" "Numberic"
	"Total Price" "Numberic"
	"Unit Price" "Numberic"
	"Quantity" "Numberic"
}

// FV 
Table FanVote {
  "Ballot Id"  "Sync Id"
  "Contact Id" "Sync Id"
  "Contact Email" Email
  "Class Year" Numeric
  "Mary J Blige" Numeric
  "Kate Bush" Numeric
  "Devo" Numeric
  "Foo Fighters" Numeric
  "The Go Gos" Numeric
  "Iron Maiden" Numeric
  "JAY Z" Numeric
  "Chaka Khan" Numeric
  "Carole King" Numeric
  "Fela Kuti" Numeric
  "LL Cool J" Numeric
  "New York Dolls" Numeric
  "Rage Against The Machine" Numeric
  "Todd Rundgren" Numeric
  "Tina Turner" Numeric
  "Dionne Warwick" Numeric
  "Beck" Numeric
  "Pat Benatar" Numeric
  "Duran Duran" Numeric
  "Eminem" Numeric
  "Eurythmics" Numeric
  "Judas Priest" Numeric
  "MC5" Numeric
  "Dolly Parton" Numeric
  "Lionel Richie" Numeric
  "Carly Simon" Numeric
  "A Tribe Called Quest" Numeric
}

// Bundle of Campaign and Campaing Members
Table Campaigns {
  Id Text
  CampaignId Lookup(Campaign)
  CampaignName__c Text
  ContactId Lookup(Contact)
  LeadId Lookup(Lead)
  LeadSource Picklist
  City Text
  State Text
  Country Text 
  PostalCode Text
  DoNotCall Checkbox
  Email EmailAddress
  FirstName Text
  LastName Text
  Phone Phone
  HasResponded Checkbox
  FirstRespondedDate date
  Status Picklist
  Title Text
  silverpop__member_id__c ExternalId
}

Table Accounts {
  Id Text
}


// > many-to-one; < one-to-many; - one-to-one; <> many-to-many
Ref: FanVote."Contact Id" <> RockHallSalesforce.CRM_Sync_ID
Ref: Campaigns.ContactId <> RockHallSalesforce.SF_Contact_Id
Ref: Campaigns.LeadId <> RockHallSalesforce.SF_Lead_Id
Ref: OppsAndLineItems."Primary Contact Id" <> RockHallSalesforce.SF_Contact_Id
Ref: OrdersAndLineItems."Bill To Contact Id" <> RockHallSalesforce.SF_Contact_Id

// https://dbdiagram.io/d/6345b19ff0018a1c5fe0cf17
